{% set name = "pybboxes" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybboxes-{{ version }}.tar.gz
  sha256: 558bfd2a7ca37def07ac95108f3b6504d728332b0c5b871df1017de5c7c1f68d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - pybboxes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/devrimcavusoglu/pybboxes
  summary: Light Weight Toolkit for Bounding Boxes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devrimcavusoglu
    - fcakyon
